// SOC Efficacy Field Descriptions (Based on SEBI CSCRF Framework)
export const FIELD_DESCRIPTIONS: Record<string, string> = {
  // Table 29: IT Asset Distribution
  'network_devices': 'Number of network devices (routers, switches, firewalls) in your infrastructure',
  'security_solutions': 'Number of dedicated security appliances and solutions deployed',
  'endpoints': 'Total count of end-user devices (laptops, desktops, mobile devices)',
  'applications': 'Number of applications monitored by SOC',
  'databases': 'Number of database servers and instances',
  'servers': 'Total count of physical and virtual servers',

  // Table 30: Asset Integration with SOC Technologies
  'pam_to_be': 'Assets that should be integrated with Privileged Access Management (auto-calculated)',
  'pam_actually': 'Assets currently integrated with PAM solution',
  'antivirus_to_be': 'Assets that should have antivirus/EPP protection (auto-calculated)',
  'antivirus_actually': 'Assets currently protected by antivirus/EPP',
  'edr_to_be': 'Assets that should have Endpoint Detection & Response (auto-calculated)',
  'edr_actually': 'Assets currently protected by EDR solution',
  'dlp_to_be': 'Assets that should have Data Loss Prevention (auto-calculated)',
  'dlp_actually': 'Assets currently protected by DLP solution',
  'dam_to_be': 'Assets that should have Database Activity Monitoring (auto-calculated)',
  'dam_actually': 'Assets currently monitored by DAM solution',
  'waf_to_be': 'Assets that should have Web Application Firewall (auto-calculated)',
  'waf_actually': 'Assets currently protected by WAF',
  'email_gateway_to_be': 'Assets that should have Email Security Gateway (auto-calculated)',
  'email_gateway_actually': 'Assets currently protected by Email Gateway',
  'web_gateway_to_be': 'Assets that should have Web Gateway/Proxy (auto-calculated)',
  'web_gateway_actually': 'Assets currently protected by Web Gateway',
  'ddos_to_be': 'Assets that should have DDoS protection (auto-calculated)',
  'ddos_actually': 'Assets currently protected by DDoS solution',
  'siem_to_be': 'Assets that should send logs to SIEM (auto-calculated)',
  'siem_actually': 'Assets currently integrated with SIEM',

  // Table 31: SOC Operations Performance
  'log_sources_in_siem': 'Number of log sources currently sending logs to SIEM',
  'total_log_sources': 'Total number of log sources that should be monitored',
  'max_log_latency_minutes': 'Maximum time delay in log processing (in minutes)',
  'technologies_on_latest_versions': 'Number of security technologies on latest/supported versions',
  'total_technologies_deployed': 'Total number of security technologies deployed',
  'open_advisories': 'Number of security advisories currently open/unresolved',
  'total_advisories': 'Total number of security advisories received',
  'technologies_with_use_cases': 'Number of technologies with defined use cases',
  'total_soc_technologies': 'Total number of SOC technologies deployed',
  'use_cases_not_triggered': 'Number of use cases that have not been triggered',
  'total_use_cases': 'Total number of use cases defined',
  'playbooks_defined': 'Number of incident response playbooks defined',
  'total_use_cases_for_playbooks': 'Total use cases that should have playbooks',
  'false_positives': 'Number of false positive alerts',
  'total_alerts_for_fp': 'Total alerts used for false positive calculation',
  'false_negatives': 'Number of false negative incidents',
  'total_alerts_for_fn': 'Total alerts used for false negative calculation',
  'threat_intel_processing_time': 'Time taken to process threat intelligence (in minutes)',
  'critical_log_verification': 'Daily verification of critical system logs (Yes/No)',
  'critical_integration_check': 'Daily check of critical integrations (Yes/No)',
  'critical_siem_rules': 'SIEM rules configured for critical systems (Yes/No)',
  'critical_privilege_check': 'Weekly privileged account audit (Yes/No)',
  'critical_backups': 'Periodic backup of SOC configurations (Yes/No)',

  // Table 32: Personnel Competency
  'l1_2years': 'Number of L1 analysts with 2 years experience',
  'l1_3years': 'Number of L1 analysts with 3 years experience',
  'l1_4years': 'Number of L1 analysts with 4 years experience',
  'l1_5years': 'Number of L1 analysts with 5+ years experience',
  'l2_6years': 'Number of L2 analysts with 6 years experience',
  'l2_7years': 'Number of L2 analysts with 7 years experience',
  'l2_8years': 'Number of L2 analysts with 8+ years experience',
  'l3_9years': 'Number of L3 analysts with 9 years experience',
  'l3_10years': 'Number of L3 analysts with 10 years experience',
  'l3_11years': 'Number of L3 analysts with 11 years experience',
  'l3_12plus_years': 'Number of L3 analysts with 12+ years experience',

  // Table 33: SOC Governance
  'total_cybersecurity_budget': 'Total annual cybersecurity budget (in currency)',
  'soc_budget': 'Budget allocated specifically for SOC operations',
  'training_budget': 'Percentage of SOC budget allocated for training',
  'it_committee_review': 'SOC performance reviewed by IT committee (Yes/No)',
  'tech_committee_recommendations': 'Technical committee recommendations submitted (Yes/No)',

  // Table 34: SOC Enhancements
  'native_dashboard': 'Using native SIEM dashboard (Yes/No)',
  'custom_dashboard': 'Custom dashboard developed for SOC (Yes/No)',
  'threat_hunting_provider': 'Threat hunting by external service provider (Yes/No)',
  'threat_hunting_internal': 'Threat hunting by internal team (Yes/No)',
  'threat_hunting_quarterly': 'Quarterly threat hunting exercises conducted (Yes/No)',
  'threat_hunting_half_yearly': 'Half-yearly threat hunting exercises conducted (Yes/No)',
  'total_hypotheses': 'Total threat hunting hypotheses created',
  'hypotheses_vulnerabilities': 'Hypotheses focused on vulnerabilities',
  'hypotheses_iocs': 'Hypotheses focused on Indicators of Compromise',
  'hypotheses_ioas': 'Hypotheses focused on Indicators of Attack',
  'threat_intel_siem': 'Threat intelligence integrated with SIEM (Yes/No)',
  'soar_actions_created': 'Total number of SOAR automation actions created',
  'soar_actions_triggered': 'Number of SOAR actions successfully triggered',
  'tech_decoy': 'Deception technology deployed (Yes/No)',
  'tech_sandboxing': 'Malware sandboxing solution deployed (Yes/No)',
  'tech_ueba': 'User and Entity Behavior Analytics deployed (Yes/No)',
  'tech_vulnerability': 'Vulnerability management solution deployed (Yes/No)',
  'tech_encrypted_traffic': 'Encrypted traffic management solution deployed (Yes/No)',
  'tech_dns_security': 'DNS security solution deployed (Yes/No)',
  'tech_ips': 'Intrusion Prevention System deployed (Yes/No)',
  'tech_data_classification': 'Data classification solution deployed (Yes/No)',
}
